### ISSUE TITLE
Increase verticality of application and add std out to the right side

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikely#27] opened 2019-06-10 10:48 UTC
In my humble opinion, the height of the application should be increased (it is a little small) and then a standard out terminal can be concatenated to the right side. I think that would be ideal.

**Comment by rogerhurwitz** [comment] 2019-06-19 04:21
Increase height of application.  Standard out request is a duplicate of issue #14.

**Closed as completed by rogerhurwitz** 2019-06-19 04:21 UTC
Labels: enhancement
