### ISSUE TITLE
Allow user to see the number of unfilled parameters left for their job

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikely#19] opened 2019-06-02 12:11 UTC
Currently, it is challenging to find all the unfilled parameters in your job. It would be nice if there was  a number that would tick down to zero as you added parameters (or something).

Maybe we can have a number for each stage in the pipeline that indicates the number of unfilled parameters.

**Comment by rogerhurwitz** [comment] 2019-06-17 04:38
Initial implementation committed to develop branch attempts uses a red background for missing parameter values.  I suspect there are some missing parameter use cases that I have not handled.  Please test.  The current implementation does not yet block the user from pushing "run" if one or more parameters values are missing.

**Comment by colehurwitz** [comment] 2019-06-17 11:54
I will check it out. Nice changes!

**Comment by rogerhurwitz** [comment] 2019-06-19 04:16
Duplicate of issue #30.

**Closed as completed by rogerhurwitz** 2019-06-19 04:16 UTC
Labels: enhancement
